/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LiveClassesRouteImport } from './routes/live-classes'
import { Route as OfferDetailRouteImport } from './routes/offer-detail'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OnDemandClassRouteImport } from './routes/on-demand-class'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProfileDeleteAccountRouteImport } from './routes/profile-delete-account'
import { Route as ProfileNotificationsRouteImport } from './routes/profile-notifications'
import { Route as ProfilePasswordRouteImport } from './routes/profile-password'
import { Route as ProfilePaymentDetailsRouteImport } from './routes/profile-payment-details'
import { Route as ProfilePersonalDetailsRouteImport } from './routes/profile-personal-details'
import { Route as ProfilePrivacyRouteImport } from './routes/profile-privacy'
import { Route as ClassesIndexRouteImport } from './routes/classes.index'
import { Route as ClassesCategoryRouteImport } from './routes/classes.$category'
import { Route as LiveClassesIndexRouteImport } from './routes/live-classes.index'
import { Route as LiveClassesSessionRouteImport } from './routes/live-classes.$session'
import { Route as ApiPublicYogaroxSplatRouteImport } from './routes/api/public/yogarox/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveClassesRoute = LiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferDetailRoute = OfferDetailRouteImport.update({
  id: '/offer-detail',
  path: '/offer-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnDemandClassRoute = OnDemandClassRouteImport.update({
  id: '/on-demand-class',
  path: '/on-demand-class',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileDeleteAccountRoute = ProfileDeleteAccountRouteImport.update({
  id: '/profile-delete-account',
  path: '/profile-delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/profile-notifications',
  path: '/profile-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePasswordRoute = ProfilePasswordRouteImport.update({
  id: '/profile-password',
  path: '/profile-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePaymentDetailsRoute = ProfilePaymentDetailsRouteImport.update({
  id: '/profile-payment-details',
  path: '/profile-payment-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePersonalDetailsRoute = ProfilePersonalDetailsRouteImport.update({
  id: '/profile-personal-details',
  path: '/profile-personal-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePrivacyRoute = ProfilePrivacyRouteImport.update({
  id: '/profile-privacy',
  path: '/profile-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassesRoute,
} as any)
const ClassesCategoryRoute = ClassesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ClassesRoute,
} as any)
const LiveClassesIndexRoute = LiveClassesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LiveClassesRoute,
} as any)
const LiveClassesSessionRoute = LiveClassesSessionRouteImport.update({
  id: '/$session',
  path: '/$session',
  getParentRoute: () => LiveClassesRoute,
} as any)
const ApiPublicYogaroxSplatRoute = ApiPublicYogaroxSplatRouteImport.update({
  id: '/api/public/yogarox/$',
  path: '/api/public/yogarox/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRouteWithChildren
  '/forum': typeof ForumRoute
  '/home': typeof HomeRoute
  '/live-classes': typeof LiveClassesRouteWithChildren
  '/offer-detail': typeof OfferDetailRoute
  '/offers': typeof OffersRoute
  '/on-demand-class': typeof OnDemandClassRoute
  '/profile': typeof ProfileRoute
  '/profile-delete-account': typeof ProfileDeleteAccountRoute
  '/profile-notifications': typeof ProfileNotificationsRoute
  '/profile-password': typeof ProfilePasswordRoute
  '/profile-payment-details': typeof ProfilePaymentDetailsRoute
  '/profile-personal-details': typeof ProfilePersonalDetailsRoute
  '/profile-privacy': typeof ProfilePrivacyRoute
  '/classes/$category': typeof ClassesCategoryRoute
  '/live-classes/$session': typeof LiveClassesSessionRoute
  '/classes/': typeof ClassesIndexRoute
  '/live-classes/': typeof LiveClassesIndexRoute
  '/api/public/yogarox/$': typeof ApiPublicYogaroxSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forum': typeof ForumRoute
  '/home': typeof HomeRoute
  '/offer-detail': typeof OfferDetailRoute
  '/offers': typeof OffersRoute
  '/on-demand-class': typeof OnDemandClassRoute
  '/profile': typeof ProfileRoute
  '/profile-delete-account': typeof ProfileDeleteAccountRoute
  '/profile-notifications': typeof ProfileNotificationsRoute
  '/profile-password': typeof ProfilePasswordRoute
  '/profile-payment-details': typeof ProfilePaymentDetailsRoute
  '/profile-personal-details': typeof ProfilePersonalDetailsRoute
  '/profile-privacy': typeof ProfilePrivacyRoute
  '/classes/$category': typeof ClassesCategoryRoute
  '/live-classes/$session': typeof LiveClassesSessionRoute
  '/classes': typeof ClassesIndexRoute
  '/live-classes': typeof LiveClassesIndexRoute
  '/api/public/yogarox/$': typeof ApiPublicYogaroxSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classes': typeof ClassesRouteWithChildren
  '/forum': typeof ForumRoute
  '/home': typeof HomeRoute
  '/live-classes': typeof LiveClassesRouteWithChildren
  '/offer-detail': typeof OfferDetailRoute
  '/offers': typeof OffersRoute
  '/on-demand-class': typeof OnDemandClassRoute
  '/profile': typeof ProfileRoute
  '/profile-delete-account': typeof ProfileDeleteAccountRoute
  '/profile-notifications': typeof ProfileNotificationsRoute
  '/profile-password': typeof ProfilePasswordRoute
  '/profile-payment-details': typeof ProfilePaymentDetailsRoute
  '/profile-personal-details': typeof ProfilePersonalDetailsRoute
  '/profile-privacy': typeof ProfilePrivacyRoute
  '/classes/$category': typeof ClassesCategoryRoute
  '/live-classes/$session': typeof LiveClassesSessionRoute
  '/classes/': typeof ClassesIndexRoute
  '/live-classes/': typeof LiveClassesIndexRoute
  '/api/public/yogarox/$': typeof ApiPublicYogaroxSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classes'
    | '/forum'
    | '/home'
    | '/live-classes'
    | '/offer-detail'
    | '/offers'
    | '/on-demand-class'
    | '/profile'
    | '/profile-delete-account'
    | '/profile-notifications'
    | '/profile-password'
    | '/profile-payment-details'
    | '/profile-personal-details'
    | '/profile-privacy'
    | '/classes/$category'
    | '/live-classes/$session'
    | '/classes/'
    | '/live-classes/'
    | '/api/public/yogarox/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forum'
    | '/home'
    | '/offer-detail'
    | '/offers'
    | '/on-demand-class'
    | '/profile'
    | '/profile-delete-account'
    | '/profile-notifications'
    | '/profile-password'
    | '/profile-payment-details'
    | '/profile-personal-details'
    | '/profile-privacy'
    | '/classes/$category'
    | '/live-classes/$session'
    | '/classes'
    | '/live-classes'
    | '/api/public/yogarox/$'
  id:
    | '__root__'
    | '/'
    | '/classes'
    | '/forum'
    | '/home'
    | '/live-classes'
    | '/offer-detail'
    | '/offers'
    | '/on-demand-class'
    | '/profile'
    | '/profile-delete-account'
    | '/profile-notifications'
    | '/profile-password'
    | '/profile-payment-details'
    | '/profile-personal-details'
    | '/profile-privacy'
    | '/classes/$category'
    | '/live-classes/$session'
    | '/classes/'
    | '/live-classes/'
    | '/api/public/yogarox/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassesRoute: typeof ClassesRouteWithChildren
  ForumRoute: typeof ForumRoute
  HomeRoute: typeof HomeRoute
  LiveClassesRoute: typeof LiveClassesRouteWithChildren
  OfferDetailRoute: typeof OfferDetailRoute
  OffersRoute: typeof OffersRoute
  OnDemandClassRoute: typeof OnDemandClassRoute
  ProfileRoute: typeof ProfileRoute
  ProfileDeleteAccountRoute: typeof ProfileDeleteAccountRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfilePasswordRoute: typeof ProfilePasswordRoute
  ProfilePaymentDetailsRoute: typeof ProfilePaymentDetailsRoute
  ProfilePersonalDetailsRoute: typeof ProfilePersonalDetailsRoute
  ProfilePrivacyRoute: typeof ProfilePrivacyRoute
  ApiPublicYogaroxSplatRoute: typeof ApiPublicYogaroxSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-classes': {
      id: '/live-classes'
      path: '/live-classes'
      fullPath: '/live-classes'
      preLoaderRoute: typeof LiveClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer-detail': {
      id: '/offer-detail'
      path: '/offer-detail'
      fullPath: '/offer-detail'
      preLoaderRoute: typeof OfferDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-demand-class': {
      id: '/on-demand-class'
      path: '/on-demand-class'
      fullPath: '/on-demand-class'
      preLoaderRoute: typeof OnDemandClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-delete-account': {
      id: '/profile-delete-account'
      path: '/profile-delete-account'
      fullPath: '/profile-delete-account'
      preLoaderRoute: typeof ProfileDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-notifications': {
      id: '/profile-notifications'
      path: '/profile-notifications'
      fullPath: '/profile-notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-password': {
      id: '/profile-password'
      path: '/profile-password'
      fullPath: '/profile-password'
      preLoaderRoute: typeof ProfilePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-payment-details': {
      id: '/profile-payment-details'
      path: '/profile-payment-details'
      fullPath: '/profile-payment-details'
      preLoaderRoute: typeof ProfilePaymentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-personal-details': {
      id: '/profile-personal-details'
      path: '/profile-personal-details'
      fullPath: '/profile-personal-details'
      preLoaderRoute: typeof ProfilePersonalDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-privacy': {
      id: '/profile-privacy'
      path: '/profile-privacy'
      fullPath: '/profile-privacy'
      preLoaderRoute: typeof ProfilePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof ClassesRoute
    }
    '/classes/$category': {
      id: '/classes/$category'
      path: '/$category'
      fullPath: '/classes/$category'
      preLoaderRoute: typeof ClassesCategoryRouteImport
      parentRoute: typeof ClassesRoute
    }
    '/live-classes/': {
      id: '/live-classes/'
      path: '/'
      fullPath: '/live-classes/'
      preLoaderRoute: typeof LiveClassesIndexRouteImport
      parentRoute: typeof LiveClassesRoute
    }
    '/live-classes/$session': {
      id: '/live-classes/$session'
      path: '/$session'
      fullPath: '/live-classes/$session'
      preLoaderRoute: typeof LiveClassesSessionRouteImport
      parentRoute: typeof LiveClassesRoute
    }
    '/api/public/yogarox/$': {
      id: '/api/public/yogarox/$'
      path: '/api/public/yogarox/$'
      fullPath: '/api/public/yogarox/$'
      preLoaderRoute: typeof ApiPublicYogaroxSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClassesRouteChildren {
  ClassesCategoryRoute: typeof ClassesCategoryRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
}

const ClassesRouteChildren: ClassesRouteChildren = {
  ClassesCategoryRoute: ClassesCategoryRoute,
  ClassesIndexRoute: ClassesIndexRoute,
}

const ClassesRouteWithChildren =
  ClassesRoute._addFileChildren(ClassesRouteChildren)

interface LiveClassesRouteChildren {
  LiveClassesSessionRoute: typeof LiveClassesSessionRoute
  LiveClassesIndexRoute: typeof LiveClassesIndexRoute
}

const LiveClassesRouteChildren: LiveClassesRouteChildren = {
  LiveClassesSessionRoute: LiveClassesSessionRoute,
  LiveClassesIndexRoute: LiveClassesIndexRoute,
}

const LiveClassesRouteWithChildren = LiveClassesRoute._addFileChildren(
  LiveClassesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassesRoute: ClassesRouteWithChildren,
  ForumRoute: ForumRoute,
  HomeRoute: HomeRoute,
  LiveClassesRoute: LiveClassesRouteWithChildren,
  OfferDetailRoute: OfferDetailRoute,
  OffersRoute: OffersRoute,
  OnDemandClassRoute: OnDemandClassRoute,
  ProfileRoute: ProfileRoute,
  ProfileDeleteAccountRoute: ProfileDeleteAccountRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfilePasswordRoute: ProfilePasswordRoute,
  ProfilePaymentDetailsRoute: ProfilePaymentDetailsRoute,
  ProfilePersonalDetailsRoute: ProfilePersonalDetailsRoute,
  ProfilePrivacyRoute: ProfilePrivacyRoute,
  ApiPublicYogaroxSplatRoute: ApiPublicYogaroxSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
